apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-project
        image: sopies/drisnq:latest
        ports:
        - containerPort: 8080