apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-api
  template:
    metadata:
      labels:
        app: movie-api
    spec:
      containers:
      - name: movie-api
        image: sopies/movie-api:latest
        ports:
        - containerPort: 8000