apiVersion: v1
kind: Service
metadata:
  name: movie-api-service
  labels:
    app: movie-api
spec:
  type: LoadBalancer
  selector:
    app: movie-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000